INSERT INTO ROLE VALUES (1, 'normal');
INSERT INTO ROLE VALUES (2, 'avansat');
INSERT INTO USERS VALUES (default ,'claudiu@tremend.com', 'ccc');
INSERT INTO USERS VALUES (default ,'maria@tremend.com', 'ccc');
INSERT INTO USERS VALUES (default, 'dragos@tremend.com', 'ccc');
INSERT INTO USER_DETAILS VALUES (1, 19, 1);
INSERT INTO BLOG_POST VALUES (1, 'content', 'title', 1);
INSERT INTO BLOG_POST VALUES (2, 'contentt', 'titlee', 1);
INSERT INTO POST_COMMENT VALUES (1, 1);
INSERT INTO POST_COMMENT VALUES (2, 2);
