INSERT INTO USERS VALUES (default, 'claudiu@tremend.com', 'ccc');
INSERT INTO USERS VALUES (default, 'maria@tremend.com', 'ccc');
INSERT INTO USERS VALUES (default, 'dragos@tremend.com', 'ccc');
INSERT INTO USER_DETAILS (id, username, email, password, age, gender, country, user_id) VALUES (1, 'claudiu', 'claudiu@tremend.com', '', 19, 'male', 'Romania', 1);
INSERT INTO USER_DETAILS (id, username, email, password, age, gender, country, user_id) VALUES (2, 'maria', 'maria@tremend.com', '', 19, 'female', 'Romania', 2);
INSERT INTO USER_DETAILS (id, username, email, password, age, gender, country, user_id) VALUES (3, 'dragos', 'dragos@tremend.com', '', 19, 'male', 'Germania', 3);
INSERT INTO POST VALUES (1, 'content', 'title', 1);
INSERT INTO POST VALUES (2, 'contentt', 'titlee', 1);
INSERT INTO POST_COMMENT VALUES (1, 1);
INSERT INTO POST_COMMENT VALUES (2, 2);
